### ISSUE TITLE
Can This tool used for DNAseq?

### ISSUE THREAD

**Issue by haoziyeung** [murphycj/AGFusion#17]
Hello,i have a tumor pair data (Tumor/Normal),and i have somatic SVs(NOT RNA-seq),just gDNA sequence,so i'm wondering can i use AGFusion for visuliaze my SV?
And Sometimes there's no png output,here's my command:
`agfusion annotate --gene5prime BCR --gene3prime ABL1 --junction5prime 23634672 --junction3prime 133729677 --out BCR-ABL1/ -db /gpfs/users/yanghao/database/bundle/agfusion/agfusion.homo_sapiens.75.db --debug`

here's my log:
2018-03-28 07:26:33,778 - AGFusion - DEBUG - Connected to the database /gpfs/users/yanghao/database/bundle/agfusion/agfusion.homo_sapiens.75.db
DEBUG:AGFusion:Connected to the database /gpfs/users/yanghao/database/bundle/agfusion/agfusion.homo_sapiens.75.db
2018-03-28 07:26:33,901 - AGFusion - DEBUG - Found gene symbol entry for BCR: ENSG00000186716
DEBUG:AGFusion:Found gene symbol entry for BCR: ENSG00000186716
2018-03-28 07:26:33,901 - AGFusion - DEBUG - SQLite - SELECT * FROM homo_sapiens_75 WHERE stable_id=="ENSG00000186716"
DEBUG:AGFusion:SQLite - SELECT * FROM homo_sapiens_75 WHERE stable_id=="ENSG00000186716"
2018-03-28 07:26:33,915 - AGFusion - DEBUG - SQLite - SELECT * FROM homo_sapiens_75_transcript WHERE transcript_id=="2386152"
DEBUG:AGFusion:SQLite - SELECT * FROM homo_sapiens_75_transcript WHERE transcript_id=="2386152"
2018-03-28 07:26:33,954 - AGFusion - DEBUG - Found gene symbol entry for ABL1: ENSG00000097007
DEBUG:AGFusion:Found gene symbol entry for ABL1: ENSG00000097007
2018-03-28 07:26:33,954 - AGFusion - DEBUG - SQLite - SELECT * FROM homo_sapiens_75 WHERE stable_id=="ENSG00000097007"
DEBUG:AGFusion:SQLite - SELECT * FROM homo_sapiens_75 WHERE stable_id=="ENSG00000097007"
2018-03-28 07:26:33,964 - AGFusion - DEBUG - SQLite - SELECT * FROM homo_sapiens_75_transcript WHERE transcript_id=="2365065"
DEBUG:AGFusion:SQLite - SELECT * FROM homo_sapiens_75_transcript WHERE transcript_id=="2365065"
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/yanghao/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/yanghao/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz.pickle
2018-03-28 07:26:34,760 - AGFusion - DEBUG - The BCR-ABL1 fusion does not produce any protein coding transcripts. No cds.fa file will be written
DEBUG:AGFusion:The BCR-ABL1 fusion does not produce any protein coding transcripts. No cds.fa file will be written
2018-03-28 07:26:34,760 - AGFusion - DEBUG - The BCR-ABL1 fusion does not produce any protein coding transcripts. No proteins.fa file will be written
DEBUG:AGFusion:The BCR-ABL1 fusion does not produce any protein coding transcripts. No proteins.fa file will be written

here is output files:
[yanghao@c01sn02 AGFusion]$ ll -ht BCR-ABL1/
total 0
-rw-r--r-- 1 yanghao eulerbioinfo 1.8K Mar 28 07:31 BCR-ABL1.exons.txt
-rw-r--r-- 1 yanghao eulerbioinfo  111 Mar 28 07:31 BCR-ABL1.protein_domains.txt
-rw-r--r-- 1 yanghao eulerbioinfo  228 Mar 28 07:31 BCR-ABL1.fusion_transcripts.txt
-rw-r--r-- 1 yanghao eulerbioinfo 6.9K Mar 28 07:31 BCR-ABL1_cdna.fa

as you can see ,there's no png
and in another situation:
` agfusion annotate --gene5prime ROS1 --gene3prime TPM3 --junction5prime 117642092 --junction3prime 154142762 --out ROS1-TPM3 -db /gpfs/users/yanghao/database/bundle/agfusion/agfusion.homo_sapiens.75.db --debug`

[yanghao@c01sn02 AGFusion]$ ll -ht ROS1-TPM3/
total 0
-rw-r--r-- 1 yanghao eulerbioinfo 2.8K Mar 28 07:28 ROS1-TPM3.exons.txt
-rw-r--r-- 1 yanghao eulerbioinfo  543 Mar 28 07:28 ROS1-TPM3.protein_domains.txt
-rw-r--r-- 1 yanghao eulerbioinfo  239 Mar 28 07:28 ROS1-TPM3.fusion_transcripts.txt
-rw-r--r-- 1 yanghao eulerbioinfo  14K Mar 28 07:28 ENST00000368508-ENST00000368530.exon.png
-rw-r--r-- 1 yanghao eulerbioinfo  14K Mar 28 07:28 ENST00000368508-ENST00000368530.png
-rw-r--r-- 1 yanghao eulerbioinfo 2.1K Mar 28 07:28 ROS1-TPM3_protein.fa
-rw-r--r-- 1 yanghao eulerbioinfo 5.9K Mar 28 07:28 ROS1-TPM3_cds.fa
-rw-r--r-- 1 yanghao eulerbioinfo 6.7K Mar 28 07:28 ROS1-TPM3_cdna.fa

as you can see ,i got 2 pngs.

*P.S: this two situation is from a same sample

So i have 2 anwsers:
1) can this tool use for DNAseq?
2) why i can't get png sometimes?

Many Thanks,And this is a great tool.

**Comment by murphycj** [comment]
For the BCR-ABL fusion, I see that Ensembl does not have a stop codon annotated for the canonical ABL transcript (ENST00000372348). This indicates to AGFusion that the transcript does not have protein coding potential. This is a limit of the ensembl database (for release 75), but I think this fusion really does have protein coding potential. You have two alternative options:

1. You can tell it to generate fusions from all transcript combinations via the following command:

`agfusion annotate --gene5prime BCR --gene3prime ABL1 --junction5prime 23634672 --junction3prime 133729677 --out BCR-ABL1/ -db agfusion.homo_sapiens.75.db --noncanonical`

2. You can use the non-canonical transcript for ABL instead:

`agfusion annotate --gene5prime BCR --gene3prime ENST00000318560 --junction5prime 23634672 --junction3prime 133729677 --out BCR-ABL1/ -db agfusion.homo_sapiens.75.db`

`can this tool use for DNAseq?`

Yes, you should be able to use it for DNAseq. All AGFusion needs as input is the genes and fusion junction coordinates.

`why i can't get png sometimes?`

For any fusion you provide it, if there is no protein coding potential then AGFusion will not output the images. Though now that I think of it, if there is no protein coding potential it should at least output the exon structure. I'll fix this.

**Comment by haoziyeung** [comment]
Thanks,it really help
