### ISSUE TITLE
Documention

### ISSUE THREAD

**Issue by ahgillmo** [murphycj/AGFusion#18]
Thank you for the tool. I really enjoy the ability to know the fusion parameters. Is it possible to get some documentation for the fusions_transcripts.txt? Specifically how do exon-exon differ from in-frame or out-of-frame?

**Comment by murphycj** [comment]
Sure, I'll update the package with some more documentation

**Comment by pintoa1-mskcc** [comment]
Where is the documentation for this?

Thanks

**Comment by pintoa1-mskcc** [comment]
Hi again! Any update on the documentation?
