### ISSUE TITLE
Strange behavior calling  fusion frame

### ISSUE THREAD

**Issue by juferban** [murphycj/AGFusion#19]
Hi,

I recently started using your tool and noticed a strange behaviour when calling the frame conservation of a fusion.

If I command below I get that my fusion is out-of-frame as expected. 
agfusion annotate \
  --gene5prime TMEM87B \
  --gene3prime MERTK \
  --junction5prime 112843681 \
  --junction3prime 112722768 \
  -db agfusion.homo_sapiens.75.db \
  -o TMEM87B-MERTK

This is out-of-frame as the donor exon has 2 bps of the last codon and the aceptor exon has 2 bps of the first codon.

Case 1:
I would expect that if I remove 1 base from the 5prime I will get a in-frame fusion and when I run the command below that is the case:
agfusion annotate \
  --gene5prime TMEM87B \
  --gene3prime MERTK \
  --junction5prime 112843680 \
  --junction3prime 112722768 \
  -db agfusion.homo_sapiens.75.db \
  -o TMEM87B-MERTK

Case 2:
Now if I try the other way around and instead I add a position to the 3prime junction I would also expect a similar in-frame fusion but that is not the case and I still get an out-of-frame result.

agfusion annotate \
  --gene5prime TMEM87B \
  --gene3prime MERTK \
  --junction5prime 112843681 \
  --junction3prime 112722769 \
  -db agfusion.homo_sapiens.75.db \
  -o TMEM87B-MERTK

Case 3:
What is also surprising is that if I move one entire codon up the results is again in-frame
agfusion annotate \
  --gene5prime TMEM87B \
  --gene3prime MERTK \
  --junction5prime 112843681 \
  --junction3prime 112722771 \
  -db agfusion.homo_sapiens.75.db \
  -o TMEM87B-MERTK

My guess is that in case 2, even if it should be an in-frame fusion the resulting fused codon is a stop codon but when I checked the sequence it seems that it is not the case.

Am I missing something?.

Thanks.

**Comment by murphycj** [comment]
Indeed what you found is a bug. I have pushed a fix. Give it a try and let me know if you have any issues
