### ISSUE TITLE
using annotate --WT option causes exception

### ISSUE THREAD

**Issue by dllahr-foghorntx** [murphycj/AGFusion#20]
Hello

I'm running agfusion annoate with the --WT option and I got the error:
```python
File "/Users/davelahr/miniconda2/envs/pyensembl/lib/python3.6/site-packages/agfusion/plot.py", line 657, in _draw_protein_length_markers
    for i in range(1, protein_length+1):
TypeError: 'float' object cannot be interpreted as an integer
```
I modified the code in question to be:
`for i in range(1, int(protein_length)+1):`

And then it worked.  Not sure if this is the best way to fix.

Thank you for the very useful software!

**Comment by murphycj** [comment]
Yeah that fix might be fine. Could you give me the command you're using so I can see why protein_length is a float? I would not think that should happen and want to be sure it is not a bigger issue.

**Comment by dllahr-foghorntx** [comment]
Sorry should have included that initially - here is the command I ran:
`agfusion annotate   --gene5prime ATRX   --gene3prime SSX2   --junction5prime 77785846   --junction3prime 52700543   -db agfusion.homo_sapiens.87.db   -o ATRX-SSX2 --WT`

**Comment by dllahr-foghorntx** [comment]
ps.  I printed out the variable `protein_length` a couple times when I ran it and it didn't have a fraction in the float, it's just that the type was float

**Comment by murphycj** [comment]
OK I found the issue and the fix is really as simple as what you used. So I pushed the fix to the main repository. Re-open this if you still have issues.
