### ISSUE TITLE
what file is used for infusion algorithm?

### ISSUE THREAD

**Issue by foxchase** [murphycj/AGFusion#22]
Dear Charlie,
what file is used as input for AGFusion from the output files generated by Infusion?
There are several output files generated by Infusion, such as fusions.txt, fusions.detailed.txt and fusions.detailed.full.txt. Thanks in advance.

**Comment by murphycj** [comment]
The fusions.txt file is currently what I support and have unit tests for.

**Comment by murphycj** [comment]
Reopen the issue if you still have issues.
