### ISSUE TITLE
rename and type not working

### ISSUE THREAD

**Issue by msquatrito** [murphycj/AGFusion#23]
Hi,
Thanks for the tool, it is very useful. I am running the latest version (1.21) with Python 2.7.14 and I am having issues with the "rename" and "type" arguments.
Running the basic usage examples I fail to change the name of the protein domains. 
Any help n this issues will be highly appreciated.
Thanks
Best,
Massimo

**Comment by murphycj** [comment]
Massimo,

Sorry for the delayed response, been busy. I patched a fix for the "rename" and "type" arguments. Let me know if you still have issues.

**Comment by murphycj** [comment]
FYI: the fix is in v1.22, which you can get either from pip or cloning the GitHub repository

**Comment by msquatrito** [comment]
"Rename" is now working. However, if you pass both the "rename" and "recolor" arguments, the recolor does not work. "recolor" works fine if you don´t pass any "rename" argument.

**Comment by murphycj** [comment]
fixed, the bug in v1.23. Give it a shot
