### ISSUE TITLE
Saving plots as pdf files

### ISSUE THREAD

**Issue by msquatrito** [murphycj/AGFusion#24]
Hi,
I am trying to save the plots as .pdf files, but the output is always a .png. I have tried to pass` --type pdf` or `--type PDF`, but I did not succeed.
How should I pass the --type argument to save as pdf?
Thanks
Best
Massimo

**Comment by murphycj** [comment]
Sorry this was a bug in my code. This has been fixed in v1.22, so  "--type pdf" should work now. Let me know if you have issues.

**Comment by msquatrito** [comment]
Thanks this solved the issue
