### ISSUE TITLE
Add gene direction to the exons output file

### ISSUE THREAD

**Issue by susannasiebert** [murphycj/AGFusion#26]
We would like to add AGfusion support the our immunotherapy toolkit pVACtools (pvactools.org, https://github.com/griffithlab/pVACtools). We would like to output not only the genomic coordinates, which we can grab from the exons files, but also the direction of transcription for the fusion (i.e. the orientation for each gene at the junction site). If i'm interpreting the output correctly the orientation can only be interpreted from the current results if there is more than one exon involved on both sides of the fusion by looking to see if coordinates increase or decrease. Would it be possible to formally add this information to the AGfusion output to help with situations where only 1 exon is reported on a fusion side?

**Comment by murphycj** [comment]
That should be no problem. Just to make sure I understand you, you want the output to include the strand of each gene partner (i.e. + or -)? Do you want this information in the table output as well as in the sequence name in the fasta file? Or just one of them?

**Comment by susannasiebert** [comment]
By strand, do you mean the orientation? If so, then yes, that's the information we need. If you could include that in both the table and the header, that would be great.

**Comment by susannasiebert** [comment]
After talking this through with my colleagues, yes, providing the transcript chromosomal orientation would be sufficient. Sorry for the confusion.

**Comment by murphycj** [comment]
Sorry about the delay here. You may or may not need this feature anymore, but I have added strand information to the header and table output. Just install the latest release: v1.25.

**Comment by susannasiebert** [comment]
Thank you for adding this feature. Feel free to close this issue.
