### ISSUE TITLE
Ensembl 96 support

### ISSUE THREAD

**Issue by stsergbg** [murphycj/AGFusion#27]
Hi,
As the docs state, the current maximal ensemble release is 92. It would be great to have the 96 ensembl release supported - so as to make the AGFusion package compatible with new releases of STAR-Fusion (which uses gencode v29). Would that be possible in future?

Best,
Sergei

**Comment by murphycj** [comment]
Sergei,
Sure I will look into this later tonight!

**Comment by murphycj** [comment]
I added support to version 95, but I cannot do 96 yet because agfusion depends on the pyensembl python package which only goes to 95. You can try asking the authors of that package to increase it, or you can fork the repository and increase it yourself: https://github.com/openvax/pyensembl
