### ISSUE TITLE
Frameshift fusions warning

### ISSUE THREAD

**Issue by stsergbg** [murphycj/AGFusion#28]
Hi!

I'm having a bit of a problem with out-of-frame fusions. When I annotate an out-of-frame fusion with:
`agfusion annotate -g5 ENST00000311922 -g3 ENST00000517315 -j5 125431262 -j3 125357219 -db agfusion.homo_sapiens.95.db --recolor "Pkinase_Tyr;red" --dpi 300 --WT`

I catch a warning:
`AGFusion - WARNING - Fusion isoform effect is not out-of-frame but CDS is not a multiple of 3!
`
Even though the `fusion_transcripts.txt` file explicitly says fusion isoform effect is out-of-frame (and it should be, and the length of CDS is indeed 686, not divisible by 3):
```
5'_gene,3'_gene,5'_transcript,3'_transcript,5'_strand,3'_strand,5'_transcript_biotype,3'_transcript_biotype,Fusion_effect,Protein_length,Protein_weight_(kD)
TRIB1,NSMCE2,ENST00000311922,ENST00000517315,+,+,protein_coding,protein_coding,out-of-frame,138,14.450594999999986
```

The warning does not affect the files in the sense that domain and exon structure still get reported (and the sequence stops at the first out-of-frame stop codon found), but still the warning seems to be a bit misinforming.

All the best,
Sergei

**Comment by murphycj** [comment]
Sergei,

Sorry for the late reply and thanks for your input! I agree with you that the warning is a bit misinforming. I have corrected it in the most recent version.

Best.
