### ISSUE TITLE
Unable to download database(agfusion.homo_sapiens.94.db)

### ISSUE THREAD

**Issue by ShahiRB** [murphycj/AGFusion#29]
Hi Charlie,

When I tried to download database (agfusion.homo_sapiens.94.db)  with the command below:
agfusion download --species homo_sapiens --release 94

I got the following output:
Downloading the AGFusion database to agfusion.homo_sapiens.94.db.gz...
Was unable to download the file https://s3.amazonaws.com/agfusion/agfusion.homo_sapiens.94.db.gz!

What can be the reasons?

Though command  "agfusion download -a"  shows homo_sapiens.94 db is available.

Thanx in advance!

Regards,
Rajendra

**Comment by murphycj** [comment]
Hi Rajendra,

Sorry about that! I added the agfusion.homo_sapiens.94.db.gz file. So you should be good to go now. Let me know if you have any more issues.

Charlie

**Comment by ShahiRB** [comment]
Your kindness Charlie! :)
