### ISSUE TITLE
Images not created for GRCh37

### ISSUE THREAD

**Issue by rhshah** [murphycj/AGFusion#3]
Hi There,

Great tool, I am trying to make plots for GRCh37 and i only get is the `*1_cdna.fa`, none of the other files and images get created. 

This is the command that i run:
`agfusion  --gene5prime ENSG00000197157  --gene3prime ENSG00000157764   --junction5prime 127389835   --junction3prime 140490224 --genome GRCh37   --out SND1-BRAF`

I am able to replicate you example for mouse genome.

Thank you for your help in advance.

Best,
Ronak

**Comment by murphycj** [comment]
Ronak,

It appears there is a bug in AGFusion where it does not properly handle fusion junctions in introns. I patched the code, so reinstall from here or pip and let me know if it works for you.

**Comment by rhshah** [comment]
Thank you for your prompt response, it does work now. 
Currently you only support Ensembl Id, are you planning to RefSeq Id ?

**Comment by murphycj** [comment]
Yes, supporting RefSeq Ids is on my list of features I want to add.
