### ISSUE TITLE
Failing on gene names containing '/'

### ISSUE THREAD

**Issue by stsergbg** [murphycj/AGFusion#31]
Hi!

This might sound impossible (and impractical, and comical) but there are actually genes in databases whose names contain slashes. This seems to create quite some problems for AGFusion when it's trying to save files using gene names in filenames. So trying to annotate THRA--THRA1/BTR fusion produces an error:
`agfusion annotate -g5 ENST00000546243 -g3 ENST00000621191 -j5 40086853 -j3 48294347 -db /agfusion.homo_sapiens.95.db -o agfusion --recolor "Pkinase_Tyr;red" --dpi 300 --WT`

> pyensembl.sequence_data:Loaded sequence dictionary from /root/.cache/pyensembl/GRCh38/ensembl95/Homo_sapiens.GRCh38.cdna.all.fa.gz.pickle
> pyensembl.sequence_data:Loaded sequence dictionary from /root/.cache/pyensembl/GRCh38/ensembl95/Homo_sapiens.GRCh38.ncrna.fa.gz.pickle
> Traceback (most recent call last):
> File "/usr/local/bin/agfusion", line 5, in <module>
>      cli.main()
> File "/usr/local/lib/python3.6/site-packages/agfusion/cli.py", line 616, in main
>      scale=args.scale
> File "/usr/local/lib/python3.6/site-packages/agfusion/cli.py", line 117, in annotate
>      middlestar=args.middlestar
> File "/usr/local/lib/python3.6/site-packages/agfusion/model.py", line 596, in save_transcript_cdna
>     'w'
> FileNotFoundError: [Errno 2] No such file or directory: '....agfusion/THRA-THRA1/BTR_cdna.fa'

All the best,
Sergei

**Comment by murphycj** [comment]
Hello,

Thanks for raising the issue. Yes, it is quite surprising to see "/" in a gene name. I change how AGFusion handles the issue though. It now replaces "/" with "-". I also change the delimiter between the genes in the fusion from "-" to "_".

The fix is in version 1.252

Thanks!
