### ISSUE TITLE
Build database for Ensembl 100

### ISSUE THREAD

**Issue by wenbostar** [murphycj/AGFusion#36]
I tried to build database for Ensembl 100 using the following command line. 

```sh
pyensembl install --species homo_sapiens --release 100
agfusion build --dir . --species homo_sapiens --release 100 --pfam pfamA.txt.gz --server ensembldb.ensembl.org
```
```
Traceback (most recent call last):
  File "/data/user/software/anaconda3/bin/agfusion", line 5, in <module>
    cli.main()
  File "/data/user/software/anaconda3/lib/python3.7/site-packages/agfusion/cli.py", line 520, in main
    builddb(args)
  File "/data/user/software/anaconda3/lib/python3.7/site-packages/agfusion/cli.py", line 204, in builddb
    args.server
  File "/data/user/software/anaconda3/lib/python3.7/site-packages/agfusion/database.py", line 68, in __init__
    self.table = ENSEMBL_MYSQL_TABLES[self.species][self.release]
KeyError: 100
```

Does anyone know how to fix this problem?

Bo

**Comment by Admera2020** [comment]
@wenbostar were you able to fix the issues? 
@murphycj  I am using STAR-fusion which uses GENCOD 33/Ensembl 99 and would like to use AGfusion to annotate the fusions.  

Best,
Nick

**Comment by haoqing12** [comment]
Thank you 😊

**Comment by wenbostar** [comment]
@Admera2020 , it works, thanks.

**Comment by YingYa** [comment]
> I managed to get around the issue. Leaving information, hopefully, it will be useful for others
> 
> * First download the release from pyensembl , currently it seems to support v100.  See [Max release 100 openvax/pyensembl#240](https://github.com/openvax/pyensembl/pull/240)
>   ` pyensembl install --species homo_sapiens --release 100`
> * Then edit file "python3.7/site-packages/agfusion/utils.py", line number 27
>   From `MAX_ENSEMBL_RELEASE = 92` to `MAX_ENSEMBL_RELEASE = 100`
> * Download the pfam file **"pfamA.txt.gz"** from here  and unzip it with bgzip "ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam33.1/database_files"
>   `bgzip -d pfamA.txt.gz`
> * Build the database for agfusion
>   `agfusion build --dir . --species homo_sapiens --release 100 --pfam pfamA.txt`
> 
> Additionally, if you see an error with MySQLdb import then install the below package `conda install -c bioconda mysqlclient`
> 
> Best,

After modified the database.py it works for me to build Ensembl 98,  hopefully, it will be useful for others:
260,266c260,266
<             """SELECT gene.gene_id, xref.display_label FROM " \
<             "gene, object_xref, xref,external_db WHERE " \
<             "gene.gene_id = object_xref.ensembl_id AND " \
<             "object_xref.ensembl_object_type = 'Gene' AND " \
<             "object_xref.xref_id = xref.xref_id AND " \
<             "xref.external_db_id = external_db.external_db_id AND " \
<             "external_db.db_name = '"""
---
>             """SELECT gene.gene_id, xref.display_label FROM \
>             gene, object_xref, xref, external_db WHERE \
>             gene.gene_id = object_xref.ensembl_id AND \
>             object_xref.ensembl_object_type = 'Gene' AND \
>             object_xref.xref_id = xref.xref_id AND \
>             xref.external_db_id = external_db.external_db_id AND \
>             external_db.db_name = '"""
