### ISSUE TITLE
Can I use the input from FusionInspector.

### ISSUE THREAD

**Issue by WangKang-Leo** [murphycj/AGFusion#49]
I am running rnafusion pipeline (https://nf-co.re/rnafusion/2.1.0) that integrated several callers, but can I use the final results from FusionInspector? Or any ideas how to parse it for AGFusion input?

**Comment by murphycj** [comment]
Hello, I'd be happy to try it out! Do you have an example output from FusionInspector? I can then take a look to see if/how to parse it.

**Comment by WangKang-Leo** [comment]
> Hello, I'd be happy to try it out! Do you have an example output from FusionInspector? I can then take a look to see if/how to parse it.

Thanks so much! Here I attached the output from FusionInspector.
[UF-3016-1102-2.FusionInspector.fusions.txt](https://github.com/murphycj/AGFusion/files/10611023/UF-3016-1102-2.FusionInspector.fusions.txt)
[UF-3016-1102-2.FusionInspector.fusions.abridged.txt](https://github.com/murphycj/AGFusion/files/10611022/UF-3016-1102-2.FusionInspector.fusions.abridged.txt)

**Comment by murphycj** [comment]
@WangKang-Leo I patched a fix in the `master` branch. Before I publish a new release, can you try it out?

```
git clone https://github.com/murphycj/AGFusion.git
cd AGFusion
pip install .
agfusion batch -f UF-3016-1102-2.FusionInspector.fusions.txt -a fusioninspector -db agfusion.homo_sapiens.95.db -o output
```

**Comment by WangKang-Leo** [comment]
Thanks for your prompt response, it runs smoothly!
